live_config_reload = true

[window]
dimensions = { columns = 128, lines = 32 }
opacity = 0.8
blur = true

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
size = 10

[colors]

cursor = { text = "#2A2A37", cursor = "#DCD7BA" }

[colors.primary]
foreground = "#DCD7BA"
background = "#1F1F28"

[colors.normal]
black = "#1F1F28"
red = "#E82424"
green = "#76946A"
yellow = "#FF9E3B"
blue = "#658594"
magenta = "#957FBB"
cyan = "#9CABCA"
white = "#DCD7BA"

[colors.bright]
black = "#2A2A37"
red = "#FF5D62"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#D27E99"
cyan = "#A3D4D5"
white = "#FAF4D4"

